[package]
name = "ruva"
version = "0.2.18"
edition = "2021"
license = "MIT"
description = "Rust Library For Event Driven Message Handling"
repository = "https://github.com/BeringLab/ruva"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ruva-core= {version="0.2.18", path="./ruva-core"}
ruva-macro= {version="0.2.18", path="./ruva-macro"}
static_assertions="1.1.0"
