[package]
name = "event-driven-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["sync"] }
downcast-rs ="*"
serde = {version="*",features=["derive"]}
serde_json = "*"
uuid = { version = "1.3.3", features = ["v4"]}
chrono = {version="*"}
async-trait = {version="*"}
futures="*"